const MILLISECONDS_PER_SECOND = 1000;
const SECONDS_PER_MINUTE = 60;
const MINUTES_PER_HOUR = 60;
const HOURS_PER_DAY = 24;
const DAYS_PER_WEEK = 7;

/**
 * Utility constant for time conversions.
 */
export const TIMING = Object.freeze({
  WEEK: {
    IN_HOURS: DAYS_PER_WEEK * HOURS_PER_DAY,
    IN_MINUTES: DAYS_PER_WEEK * MINUTES_PER_HOUR * HOURS_PER_DAY,
    IN_SECONDS:
      DAYS_PER_WEEK * SECONDS_PER_MINUTE * MINUTES_PER_HOUR * HOURS_PER_DAY,
    IN_MILLISECONDS:
      DAYS_PER_WEEK *
      MILLISECONDS_PER_SECOND *
      SECONDS_PER_MINUTE *
      MINUTES_PER_HOUR *
      HOURS_PER_DAY,
  },
  DAY: {
    IN_HOURS: HOURS_PER_DAY,
    IN_MINUTES: MINUTES_PER_HOUR * HOURS_PER_DAY,
    IN_SECONDS: SECONDS_PER_MINUTE * MINUTES_PER_HOUR * HOURS_PER_DAY,
    IN_MILLISECONDS:
      MILLISECONDS_PER_SECOND *
      SECONDS_PER_MINUTE *
      MINUTES_PER_HOUR *
      HOURS_PER_DAY,
  },
  HOUR: {
    IN_MINUTES: MINUTES_PER_HOUR,
    IN_SECONDS: SECONDS_PER_MINUTE * MINUTES_PER_HOUR,
    IN_MILLISECONDS:
      MILLISECONDS_PER_SECOND * SECONDS_PER_MINUTE * MINUTES_PER_HOUR,
  },
  MINUTE: {
    IN_SECONDS: SECONDS_PER_MINUTE,
    IN_MILLISECONDS: MILLISECONDS_PER_SECOND * SECONDS_PER_MINUTE,
  },
  SECOND: {
    IN_MILLISECONDS: MILLISECONDS_PER_SECOND,
  },
});
