/**
 * Represents the types of documents that can be processed.
 */
export enum DOCUMENT_FILE_TYPE {
  OTHER = 'OTHER',
  BANK_STATEMENT = 'ACCOUNT_STATEMENT_BANK',
  FORM_1040 = '1040',
  FORM_1040_SCH_C = '1040SC',
  FORM_1099_DIV = '1099DIV',
  FORM_1099_INT = '1099INT',
  FORM_1099_MISC = '1099MISC',
  FORM_1099_NEC = '1099NEC',
  FORM_1099_R = '1099R',
  FORM_W2 = 'W2',
  FORM_W9 = 'W9',
  MORTGAGE_STATEMENT = 'MORTGAGE_STATEMENT',
  PAYSTUB = 'PAYSTUB',
  RETIREMENT_INVESTMENT_STATEMENT = 'RETIREMENT_INVESTMENT_STATEMENT',
  UNSUPPORTED = 'UNSUPPORTED',
}

/**
 * Represents the file processors available for processing the document types.
 */
export enum DOCUMENT_FILE_PROCESSOR {
  FORM_PARSER_PROCESSOR = 'FORM_PARSER_PROCESSOR',
  BANK_STATEMENT_PROCESSOR = 'BANK_STATEMENT_PROCESSOR',
  FORM_1040_PROCESSOR = 'FORM_1040_PROCESSOR',
  FORM_1040SCH_C_PROCESSOR = 'FORM_1040SCH_C_PROCESSOR',
  FORM_1099DIV_PROCESSOR = 'FORM_1099DIV_PROCESSOR',
  FORM_1099INT_PROCESSOR = 'FORM_1099INT_PROCESSOR',
  FORM_1099MISC_PROCESSOR = 'FORM_1099MISC_PROCESSOR',
  FORM_1099NEC_PROCESSOR = 'FORM_1099NEC_PROCESSOR',
  FORM_1099R_PROCESSOR = 'FORM_1099R_PROCESSOR',
  FORM_W2_PROCESSOR = 'FORM_W2_PROCESSOR',
  FORM_W9_PROCESSOR = 'FORM_W9_PROCESSOR',
  MORTGAGE_STATEMENT_PROCESSOR = 'MORTGAGE_STATEMENT_PROCESSOR',
  PAYSTUB_PROCESSOR = 'PAYSTUB_PROCESSOR',
  RETIREMENT_INVESTMENT_STATEMENT_PROCESSOR = 'RETIREMENT_INVESTMENT_STATEMENT_PROCESSOR',
}

/**
 * Represents the mapping of document file processors to the document types they support.
 */
export const PROCESSOR_SUPPORTED_DOCUMENT_TYPES = {
  [DOCUMENT_FILE_PROCESSOR.FORM_PARSER_PROCESSOR]: [DOCUMENT_FILE_TYPE.OTHER],
  [DOCUMENT_FILE_PROCESSOR.BANK_STATEMENT_PROCESSOR]: [
    DOCUMENT_FILE_TYPE.BANK_STATEMENT,
  ],
  [DOCUMENT_FILE_PROCESSOR.FORM_1040_PROCESSOR]: [
    DOCUMENT_FILE_TYPE.FORM_1040,
    DOCUMENT_FILE_TYPE.FORM_1040_SCH_C,
  ],
  [DOCUMENT_FILE_PROCESSOR.FORM_1040SCH_C_PROCESSOR]: [
    DOCUMENT_FILE_TYPE.FORM_1040_SCH_C,
  ],
  [DOCUMENT_FILE_PROCESSOR.FORM_1099DIV_PROCESSOR]: [
    DOCUMENT_FILE_TYPE.FORM_1099_DIV,
  ],
  [DOCUMENT_FILE_PROCESSOR.FORM_1099INT_PROCESSOR]: [
    DOCUMENT_FILE_TYPE.FORM_1099_INT,
  ],
  [DOCUMENT_FILE_PROCESSOR.FORM_1099MISC_PROCESSOR]: [
    DOCUMENT_FILE_TYPE.FORM_1099_MISC,
  ],
  [DOCUMENT_FILE_PROCESSOR.FORM_1099NEC_PROCESSOR]: [
    DOCUMENT_FILE_TYPE.FORM_1099_NEC,
  ],
  [DOCUMENT_FILE_PROCESSOR.FORM_1099R_PROCESSOR]: [
    DOCUMENT_FILE_TYPE.FORM_1099_R,
  ],
  [DOCUMENT_FILE_PROCESSOR.FORM_W2_PROCESSOR]: [DOCUMENT_FILE_TYPE.FORM_W2],
  [DOCUMENT_FILE_PROCESSOR.FORM_W9_PROCESSOR]: [DOCUMENT_FILE_TYPE.FORM_W9],
  [DOCUMENT_FILE_PROCESSOR.MORTGAGE_STATEMENT_PROCESSOR]: [
    DOCUMENT_FILE_TYPE.MORTGAGE_STATEMENT,
  ],
  [DOCUMENT_FILE_PROCESSOR.PAYSTUB_PROCESSOR]: [DOCUMENT_FILE_TYPE.PAYSTUB],
  [DOCUMENT_FILE_PROCESSOR.RETIREMENT_INVESTMENT_STATEMENT_PROCESSOR]: [
    DOCUMENT_FILE_TYPE.RETIREMENT_INVESTMENT_STATEMENT,
  ],
} satisfies Record<DOCUMENT_FILE_PROCESSOR, DOCUMENT_FILE_TYPE[]>;

/**
 * Represents the mapping of document file types to their respective processors.
 */
export const DOCUMENT_TYPE_PROCESSOR = Object.entries(
  PROCESSOR_SUPPORTED_DOCUMENT_TYPES
).reduce(
  (acc, [processor, types]) => {
    types.forEach((type) => {
      acc[type] = processor as DOCUMENT_FILE_PROCESSOR;
    });
    return acc;
  },
  {} as Record<DOCUMENT_FILE_TYPE, DOCUMENT_FILE_PROCESSOR>
);
